/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.utp.view;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import pe.edu.utp.controller.DetallePedidoController;
import pe.edu.utp.controller.HistorialController;
import pe.edu.utp.model.DetallePedido;

/**
 *
 * @author BRANDY
 */
public class JFActualizarDetalle extends javax.swing.JFrame {

    HistorialController objHistorialControl = new HistorialController();
    /**
     * Creates new form JFActualizarProducto
     */
    private DetallePedido detalleViejo, detalle;
    JFNuevoPedidoProducto frameDetalle = null;
    JPActualizarPedido panelPedido = null;
    DetallePedidoController objDetalleControl = new DetallePedidoController();

    public JFActualizarDetalle() {
        initComponents();
    }

    public JFActualizarDetalle(DetallePedido detalle) {
        initComponents();
        this.detalleViejo = detalle;
        this.detalle = detalle;
    }

    public void recibirDatos(DetallePedido detalle, JPActualizarPedido panelDetalle) {
        this.detalleViejo = detalle;
        this.detalle = detalle;
        this.panelPedido = panelDetalle;
        mostrarInformacion();
    }

    public void recibirDatos(DetallePedido detalle, JFNuevoPedidoProducto frameDetalle) {
        this.detalleViejo = detalle;
        this.detalle = detalle;
        this.frameDetalle = frameDetalle;
        mostrarInformacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNumPedido = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblPrecio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Actualizar Detalle del Producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        lblNombre.setForeground(new java.awt.Color(242, 242, 242));
        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 140, -1));

        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Producto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 60, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("# de Pedido:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 80, -1));

        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("SubTotal: S/");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 70, -1));

        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Cantidad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, -1));

        lblNumPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumPedido.setForeground(new java.awt.Color(242, 242, 242));
        lblNumPedido.setText("0");
        getContentPane().add(lblNumPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        lblSubTotal.setForeground(new java.awt.Color(242, 242, 242));
        lblSubTotal.setText("0.00");
        getContentPane().add(lblSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 80, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 120, 40));

        lblPrecio.setForeground(new java.awt.Color(242, 242, 242));
        lblPrecio.setText("0.00");
        getContentPane().add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 80, -1));

        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("Precio: S/");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 60, -1));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 90, -1));

        jButton2.setText("Actualizar Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/fondo 3.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        actualizarInformacion();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (frameDetalle != null) {
            actualizarDetalleLista();
            frameDetalle.actualizarTablaDetallePedido();
        } else {
            actualizarDetalleHashMap();
        }
        //PILAS: AGREGAR AL HISTORIAL
        String fechaActual = LocalDate.now().toString();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
        String horaActual = LocalTime.now().format(formatter);
        String actividad = "Se actualizo un producto del pedido";
        objHistorialControl.agregarHistorial(fechaActual, horaActual, actividad);
        //-----
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumPedido;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
  private void mostrarInformacion() {
        if (frameDetalle == null) {
            lblNumPedido.setText(String.valueOf(detalle.getPedido().getId_pedido()));
        } else {
            lblNumPedido.setText(String.valueOf(frameDetalle.idPedido));
        }
        txtCantidad.setText(String.valueOf(detalle.getCantidad()));
        lblNombre.setText(detalle.getLibro().toString());
        lblPrecio.setText(String.valueOf(detalle.getLibro().getPrecio()));
        lblSubTotal.setText(String.valueOf(detalle.getSubtotal()));
    }

    private void actualizarInformacion() {
        int cant = Integer.parseInt(txtCantidad.getText().trim());
        double precio = Double.parseDouble(lblPrecio.getText());
        double subTotal = cant * precio;
        lblSubTotal.setText(String.valueOf(subTotal));
    }

    private void actualizarDetalleLista() {
        int cant = Integer.parseInt(txtCantidad.getText().trim());
        double subtotal = Double.parseDouble(lblSubTotal.getText());
        detalle.setCantidad(cant);
        detalle.setSubtotal(subtotal);
        frameDetalle.lista.actualizar(detalleViejo, detalle);
    }

    private void actualizarDetalleHashMap() {
        int cant = Integer.parseInt(txtCantidad.getText().trim());
        double subtotal = Double.parseDouble(lblSubTotal.getText());
        detalle.setCantidad(cant);
        detalle.setSubtotal(subtotal);

        for (DetallePedido producto : panelPedido.productosPorPedido.get(detalle.getPedido().getId_pedido())) {
            if (detalle.equals(producto)) {
                producto = detalle;
            }
        }

        objDetalleControl.guardarDetallePedido(cant, subtotal, detalle.getLibro(), detalle.getPedido());
    }
}
