/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.utp.view;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import pe.edu.utp.controller.HistorialController;
import pe.edu.utp.controller.PedidoController;
import pe.edu.utp.model.Pedido;

/**
 *
 * @author BRANDY
 */
public class JFActualizarPedido extends javax.swing.JFrame {

    private Pedido pedido;
    PedidoController objPedidoControl = new PedidoController();
    HistorialController objHistorialControl = new HistorialController();
    
    public JFActualizarPedido(Pedido pedido) {
        initComponents();
        this.pedido = pedido;
        actualizarInformacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblNumPedido = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblFechaPedido = new javax.swing.JLabel();
        boxEstado = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Actualizar Estado del Pedido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 330, 30));

        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Total : S/");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Num. Pedido:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Cliente:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Empleado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Fecha del  Pedido:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Estado:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, 20));

        lblNumPedido.setForeground(new java.awt.Color(242, 242, 242));
        lblNumPedido.setText("0");
        getContentPane().add(lblNumPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 200, -1));

        lblTotal.setForeground(new java.awt.Color(242, 242, 242));
        lblTotal.setText("0");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 220, -1));

        lblCliente.setForeground(new java.awt.Color(242, 242, 242));
        lblCliente.setText("0");
        getContentPane().add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 210, -1));

        lblEmpleado.setForeground(new java.awt.Color(242, 242, 242));
        lblEmpleado.setText("0");
        getContentPane().add(lblEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 220, -1));

        lblFechaPedido.setForeground(new java.awt.Color(242, 242, 242));
        lblFechaPedido.setText("0");
        getContentPane().add(lblFechaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 240, -1));

        boxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Listo para Recoger", "Entregado", "Cancelado" }));
        getContentPane().add(boxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 110, -1));

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      guardarPedido();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxEstado;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblFechaPedido;
    private javax.swing.JLabel lblNumPedido;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
  private void actualizarInformacion(){
      lblNumPedido.setText(String.valueOf(pedido.getId_pedido()));
      lblCliente.setText(pedido.getCliente().toString());
      lblEmpleado.setText(pedido.getEmpleado().toString());
      lblFechaPedido.setText(pedido.getFecha_pedido());
      double total = pedido.getMonto() + pedido.getIgv();
      lblTotal.setText(String.valueOf(total)); 
      boxEstado.setSelectedItem(pedido.getEstado());
  }
  
  private void guardarPedido(){
      String estado = boxEstado.getSelectedItem().toString();
      pedido.setEstado(estado);
      objPedidoControl.actualizarPedido(pedido.getId_pedido(),pedido.getFecha_pedido(),pedido.getMonto(),
              pedido.getEstado(),pedido.getIgv(), pedido.getCliente(), pedido.getEmpleado() );
      JOptionPane.showMessageDialog(null, "SE GUARDO CORRECTAMENTE");
      //PILAS: AGREGAR AL HISTORIAL
       String fechaActual = LocalDate.now().toString();
       DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
       String horaActual = LocalTime.now().format(formatter);
       String actividad = "Se agrego actualizo el estado de un pedido";
       objHistorialControl.agregarHistorial(fechaActual, horaActual, actividad);
       //----
      this.dispose();
  }


}
