/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.utp.view;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import pe.edu.utp.model.Cliente;
import pe.edu.utp.controller.ClienteController;
import pe.edu.utp.controller.HistorialController;

/**
 *
 * @author USUARIO
 */
public class JFNuevoCliente extends javax.swing.JFrame {

    /**
     * Creates new form NuevoUsuario
     */
    ClienteController objClienteControl = new ClienteController();
    HistorialController objHistorialControl = new HistorialController();
    
    public JFNuevoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Nombres = new javax.swing.JTextField();
        txt_ApellidoPaterno = new javax.swing.JTextField();
        txt_ApellidoMaterno = new javax.swing.JTextField();
        txt_Telefono = new javax.swing.JTextField();
        txt_Correo = new javax.swing.JTextField();
        txt_Direccion = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabelFondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NUEVO CLIENTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombres:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido Paterno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo Electrónico:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellido Materno:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Direccion:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        txt_Nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombresActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 170, -1));

        txt_ApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApellidoPaternoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 170, -1));

        txt_ApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApellidoMaternoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 170, -1));

        txt_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 170, -1));

        txt_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 170, -1));

        txt_Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 170, -1));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregar.setText("GUARDAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 120, 30));

        jLabelFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/fondo 3.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombresActionPerformed

    private void txt_ApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidoPaternoActionPerformed

    private void txt_ApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidoMaternoActionPerformed

    private void txt_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TelefonoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       agregarCliente();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txt_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CorreoActionPerformed

    private void txt_DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DireccionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelFondo1;
    private javax.swing.JTextField txt_ApellidoMaterno;
    private javax.swing.JTextField txt_ApellidoPaterno;
    private javax.swing.JTextField txt_Correo;
    private javax.swing.JTextField txt_Direccion;
    private javax.swing.JTextField txt_Nombres;
    private javax.swing.JTextField txt_Telefono;
    // End of variables declaration//GEN-END:variables

  //AGREGAR UN CLIENTE
 private void agregarCliente(){
   //OBTENER DATOS INGRESADOS
   String nombre,apellidoPa,apellidoMa,telefono,correoElectronico,direccion;
   nombre = txt_Nombres.getText().trim();
   apellidoPa = txt_ApellidoPaterno.getText().trim();
   apellidoMa = txt_ApellidoMaterno.getText().trim();
   telefono = txt_Telefono.getText().trim();
   correoElectronico = txt_Correo.getText().trim();
   direccion = txt_Direccion.getText().trim();
   
   //ENVIAR AL CONTROLLER PARA QUE LO PROCESE
   boolean confirmacion = objClienteControl.guardarCliente(nombre,apellidoPa,
           apellidoMa,correoElectronico,telefono,direccion);
   
   //CONFIRMAR LA AGREGACION
   if(confirmacion){
       JOptionPane.showMessageDialog(null, "Se guardo correctamente");
       //LIMPIAR LOS TEXTFIELDS
       limpiar();
       //PILAS: AGREGAR AL HISTORIAL
       String fechaActual = LocalDate.now().toString();
       DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
       String horaActual = LocalTime.now().format(formatter);
       String actividad = "Se agrego un nuevo cliente";
       objHistorialControl.agregarHistorial(fechaActual, horaActual, actividad);
   }else{
       JOptionPane.showMessageDialog(null, "Algo paso");
   }
 }
 
 //LIMPIAR LOS TEXTFIELDS
 private void limpiar(){
    txt_ApellidoMaterno.setText("");
    txt_ApellidoPaterno.setText("");
    txt_Correo.setText("");
    txt_Direccion.setText("");
    txt_Nombres.setText("");
    txt_Telefono.setText("");
    txt_Nombres.requestFocus();
}
 
 


}
