/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.utp.view;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import pe.edu.utp.controller.HistorialController;
import pe.edu.utp.controller.UsuarioController;


/**
 *
 * @author USUARIO
 */
public class JFNuevoUsuario extends javax.swing.JFrame {

    UsuarioController objUsuarioControl = new UsuarioController();
    HistorialController objHistorialControl = new HistorialController();
    
    public JFNuevoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Nombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_ApellidoPaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ApellidoMaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_CorreoElectronico = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Dni = new javax.swing.JTextField();
        box_Area = new javax.swing.JComboBox<>();
        txt_FechaContratacion = new javax.swing.JTextField();
        jLabel_fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombres:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 60, 20));

        txt_Nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombresActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 190, -1));

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido Materno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        getContentPane().add(txt_ApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 190, -1));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha de contratacion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, -1));
        getContentPane().add(txt_ApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 190, -1));

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correo Electronico:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jButton1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 130, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Área:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));
        getContentPane().add(txt_CorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 190, -1));

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellido Paterno:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DNI:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));
        getContentPane().add(txt_Dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 190, -1));

        box_Area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administracion", "Ventas", "Almacen", "Atencion al Cliente" }));
        getContentPane().add(box_Area, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 190, -1));

        txt_FechaContratacion.setText("yyyy-mm-dd");
        getContentPane().add(txt_FechaContratacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 190, -1));

        jLabel_fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/fondo 3.jpg"))); // NOI18N
        getContentPane().add(jLabel_fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombresActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     agregarUsuario();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_Area;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_fondo1;
    private javax.swing.JTextField txt_ApellidoMaterno;
    private javax.swing.JTextField txt_ApellidoPaterno;
    private javax.swing.JTextField txt_CorreoElectronico;
    private javax.swing.JTextField txt_Dni;
    private javax.swing.JTextField txt_FechaContratacion;
    private javax.swing.JTextField txt_Nombres;
    // End of variables declaration//GEN-END:variables
//AGREGAR USUARIO(EMPLEADO)
private void agregarUsuario(){
  //OBTENER LOS DATOS
  String nombres,apellidoPaterno,apellidoMaterno,area,fechaContratacion,correo;
  int dni;
  nombres = txt_Nombres.getText();
  apellidoPaterno = txt_ApellidoPaterno.getText();
  apellidoMaterno = txt_ApellidoMaterno.getText();
  area = box_Area.getSelectedItem().toString();
  fechaContratacion = txt_FechaContratacion.getText();
  dni = Integer.parseInt(txt_Dni.getText());
  correo = txt_CorreoElectronico.getText();
  
  //AGREGAR USUARIO
  boolean confirmacion = objUsuarioControl.guardarUsuario(nombres, apellidoPaterno, apellidoMaterno, 
          area, fechaContratacion, dni, correo);
  
  //CONFIRMAR LA AGREGACION
   if(confirmacion){
       JOptionPane.showMessageDialog(null, "Se guardo correctamente");
       //LIMPIAR LOS TEXTFIELDS
       limpiar();
       //PILAS: AGREGAR AL HISTORIAL
       String fechaActual = LocalDate.now().toString();
       DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
       String horaActual = LocalTime.now().format(formatter);
       String actividad = "Se agrego un nuevo usuario";
       objHistorialControl.agregarHistorial(fechaActual, horaActual, actividad);
   }else{
       JOptionPane.showMessageDialog(null, "Algo paso");
   }
  
}  
    
private void limpiar(){
    txt_Nombres.setText("");
    txt_ApellidoMaterno.setText("");
    txt_ApellidoPaterno.setText("");
    txt_CorreoElectronico.setText("");
    txt_Dni.setText("");
    txt_FechaContratacion.setText("yyyy-mm-dd");
    }
}


