/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.utp.view;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import pe.edu.utp.controller.AutorController;
import pe.edu.utp.controller.CategoriaController;
import pe.edu.utp.controller.EditorialController;
import pe.edu.utp.controller.HistorialController;
import pe.edu.utp.controller.ProductoController;
import pe.edu.utp.model.*;

/**
 *
 * @author USUARIO
 */
public class JFNuevoProducto extends javax.swing.JFrame {

    ProductoController objProductoControl = new ProductoController();
    EditorialController objEditorialControl = new EditorialController();
    AutorController objAutorControl = new AutorController();
    CategoriaController objCategoriaControl = new CategoriaController();
    HistorialController objHistorialControl = new HistorialController();

    public JFNuevoProducto() {
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxCategoria = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        txtIdioma = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        boxEditorial = new javax.swing.JComboBox<>();
        boxAutor = new javax.swing.JComboBox<>();
        jLabel_fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(boxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 160, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Autor:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NUEVO PRODUCTO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Titulo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Año:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Editorial:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Categoria:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Idioma:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cantidad:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Precio:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 160, -1));

        txtAño.setText("YYYY-MM-DD");
        txtAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAñoActionPerformed(evt);
            }
        });
        getContentPane().add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 160, -1));
        getContentPane().add(txtIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 160, -1));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 160, -1));
        getContentPane().add(txtIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 160, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ISBN:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 160, -1));

        getContentPane().add(boxEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 160, -1));

        getContentPane().add(boxAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 160, -1));

        jLabel_fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/fondo 3.jpg"))); // NOI18N
        getContentPane().add(jLabel_fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñoActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        guardarProducto();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> boxAutor;
    private javax.swing.JComboBox<Object> boxCategoria;
    private javax.swing.JComboBox<Object> boxEditorial;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_fondo1;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
   private void guardarProducto() {
        String titulo, año, idioma;
        long isbn;
        Autor autor;
        Categoria categoria;
        Editorial editorial;
        int cantidad;
        double precio;

        titulo = txtTitulo.getText();
        año = txtAño.getText();
        idioma = txtIdioma.getText();
        isbn = Long.parseLong(txtIsbn.getText());
        autor = (Autor) boxAutor.getSelectedItem();
        categoria = (Categoria) boxCategoria.getSelectedItem();
        editorial = (Editorial) boxEditorial.getSelectedItem();
        cantidad = Integer.parseInt(txtCantidad.getText());
        precio = Double.parseDouble(txtPrecio.getText());

        Producto producto = new Producto(titulo, autor, editorial, categoria, isbn, año, idioma, precio, cantidad);

        //GUARDAR LIBRO
        boolean confirmacion = objProductoControl.guardarProducto(producto);

        if (confirmacion) {
            JOptionPane.showMessageDialog(null, "Se guardo correctamente");
            //LIMPIAR LOS TEXTFIELDS
            limpiar();
            //PILAS: AGREGAR AL HISTORIAL
            String fechaActual = LocalDate.now().toString();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
            String horaActual = LocalTime.now().format(formatter);
            String actividad = "Se agrego un nuevo producto";
            objHistorialControl.agregarHistorial(fechaActual, horaActual, actividad);
        } else {
            JOptionPane.showMessageDialog(null, "Algo paso");
        }

    }

    private void limpiar() {
        txtTitulo.setText("");
        txtAño.setText("yyyy-mm-dd");
        txtIdioma.setText("");
        txtIsbn.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");
    }

    private void cargarDatos() {
        List<Autor> objAutores = objAutorControl.obtenerTodosLosAutores();
        List<Categoria> objCategorias = objCategoriaControl.obtenerTodasLasCategorias();
        List<Editorial> objEditoriales = objEditorialControl.obtenerTodasLasEditoriales();

        for (Editorial objEditorial : objEditoriales) {
            boxEditorial.addItem(objEditorial);
        }

        for (Autor objAutor : objAutores) {
            boxAutor.addItem(objAutor);
        }

        for (Categoria objCategoria : objCategorias) {
            boxCategoria.addItem(objCategoria);
        }

    }

}
