package pe.edu.utp.view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.edu.utp.model.Cliente;
import pe.edu.utp.controller.ClienteController;

/**
 *
 * @author USUARIO
 */
public class JFNuevoPedidoCliente extends javax.swing.JFrame {

    ClienteController objClienteControl = new ClienteController();
    private int id;
    
    /**
     * Creates new form NuevoPedido
     */
    public JFNuevoPedidoCliente() {
        initComponents();
        this.actualizarTablaCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnElegirCliente = new javax.swing.JButton();
        btnClienteNuevo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AÑADIR PEDIDO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Elige un cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        btnElegirCliente.setBackground(new java.awt.Color(153, 255, 153));
        btnElegirCliente.setText("Elegir Cliente");
        btnElegirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnElegirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 110, -1));

        btnClienteNuevo.setBackground(new java.awt.Color(51, 102, 255));
        btnClienteNuevo.setText("Cliente Nuevo");
        btnClienteNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnClienteNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 110, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Telefono", "Direccion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 500, 290));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/fondo 3.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void btnElegirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirClienteActionPerformed
        elegirCliente();
    }//GEN-LAST:event_btnElegirClienteActionPerformed

    private void btnClienteNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteNuevoActionPerformed
        nuevoCliente();

    }//GEN-LAST:event_btnClienteNuevoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteNuevo;
    private javax.swing.JButton btnElegirCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    //CREAR TABLA
    private DefaultTableModel crearTabla() {
        DefaultTableModel objModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Todas las celdas no son editables
            }
        ;
        };
        String[] columna = {
            "ID", "Nombre Completo", "Telefono", "Direccion"
        };
        objModel.setColumnIdentifiers(columna);
        //Estableciendo el modelo al jtable
        //Colocando el inventario de la bd a cada fila de la tabla

        return objModel;
    }

    public void enviarDato(int id) {
        JFNuevoPedidoProducto objPedido = new JFNuevoPedidoProducto();
        objPedido.setLocationRelativeTo(null);
        objPedido.setVisible(true);
        objPedido.recibirDato(id);
        this.dispose();
    }

    public void actualizarTablaCliente() {
        List<Cliente> clientes = objClienteControl.obtenerTodosLosClientes();
        DefaultTableModel objModel = crearTabla();

        for (Cliente cliente : clientes) {
            objModel.addRow(new Object[]{
                cliente.getId_cliente(),
                cliente.toString(),
                cliente.getTelefono(),
                cliente.getDireccion()
            });
        }

        jTable1.setModel(objModel);
    }

    private void nuevoCliente() {
        JFNuevoCliente objNuevoCliente = new JFNuevoCliente();
        objNuevoCliente.setLocationRelativeTo(null);
        objNuevoCliente.setVisible(true);
    }

    private void elegirCliente() {
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada != -1) {
            // Obtener datos de la fila seleccionada
            id = (int) jTable1.getValueAt(filaSeleccionada, 0);
            enviarDato(id);
        } else {
            JOptionPane.showMessageDialog(null, "No se selecciono ningun Cliente");
        }
    }

}
