/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pe.edu.utp.view;

/**
 *
 * @author BRANDY
 */
public class JPInicio extends javax.swing.JPanel {

    /**
     * Creates new form JPInicio
     */
    public JPInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 255));
        setMinimumSize(new java.awt.Dimension(820, 600));
        setPreferredSize(new java.awt.Dimension(820, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("LIBRERO ENCANTADO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 260, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><div style='text-align: justify; width: 200px;'>Librería Encantada es una acogedora librería independiente dedicada a ofrecer una amplia selección de libros de diversos géneros y autores. Con un compromiso firme hacia el fomento de la lectura y el desarrollo cultural de la comunidad, nuestra librería se distingue por su cálido ambiente y su atención personalizada. Además de nuestra extensa colección de libros nuevos y usados, organizamos eventos literarios, talleres de escritura y clubes de lectura para todas las edades.</div></html>");
        jLabel2.setToolTipText("");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 280, 190));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/freepik-export-20240523181411P82b (1).png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 0, -1, 600));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
