/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pe.edu.utp.view;

import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.List;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import pe.edu.utp.controller.ProductoController;
import pe.edu.utp.model.Producto;

/**
 *
 * @author LAB-USR-ATE
 */
public class JPReporteStock extends javax.swing.JPanel {

    ProductoController objProductoControl = new ProductoController();
    private List<Producto> productos = null;

    public JPReporteStock() {
        initComponents();
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(820, 600));
        setPreferredSize(new java.awt.Dimension(820, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("REPORTE STOCK");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tiulo", "Autor", "Fecha Publicacion", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 740, 390));

        jLabel2.setText("Buscar:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 200, -1));

        btnBuscar.setBackground(new java.awt.Color(153, 204, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/buscar.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 75, 40, 30));

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setText("PDF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 80, 30));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setText("Ordenar(Stock)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 120, 30));

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/actualizar-flecha.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, 40, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarTabla();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ordenarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pdf();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    //CREAR TABLA
    private DefaultTableModel crearTabla() {
        DefaultTableModel objModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Todas las celdas no son editables
            }
        ;
        };
        String columna[] = {
            "Id", "Titulo", "Autor", "Editorial",
            "Categoria", "ISBN", "Publicacion", "Idioma", "Precio", "Stock"
        };
        objModel.setColumnIdentifiers(columna);
        //Estableciendo el modelo al jtable
        //Colocando el inventario de la bd a cada fila de la tabla

        return objModel;
    }

    //ESTABLECER DATOS EN LA TABLA
    private void actualizarTabla() {
        //crear tabla
        DefaultTableModel objModel = crearTabla();

        productos = objProductoControl.obtenerTodosLosProductos();

        //COLOCAR CADA UNO DE LOS DATOS
        for (Producto objProducto : productos) {
            objModel.addRow(new Object[]{objProducto.getId_libro(), objProducto.getTitulo(),
                objProducto.getAutor().toString(), objProducto.getEditorial().toString(),
                objProducto.getCategoria().toString(),
                objProducto.getIsbn(), objProducto.getFecha_publicacion(), objProducto.getIdioma(),
                objProducto.getPrecio(), objProducto.getCantidad()});
        }

        jTable1.setModel(objModel);
    }

    //ORDENAR TABLA
    private void ordenarTabla() {
        //crear modelo tabla
        DefaultTableModel objModel = crearTabla();
        //ordenar lista de productos
        quickSort(productos, 0, productos.size() - 1);

        for (Producto objProducto : productos) {
            objModel.addRow(new Object[]{objProducto.getId_libro(), objProducto.getTitulo(),
                objProducto.getAutor().toString(), objProducto.getEditorial().toString(),
                objProducto.getCategoria().toString(),
                objProducto.getIsbn(), objProducto.getFecha_publicacion(), objProducto.getIdioma(),
                objProducto.getPrecio(), objProducto.getCantidad()});
        }

        jTable1.setModel(objModel);
    }

    //Buscar tabla
    private void buscarTabla() {
        //crear modelo tabla
        DefaultTableModel objModel = crearTabla();
        String titulo = txtBuscar.getText().trim();
        //ordenar y buscar
        quickSortTitulo(productos, 0, productos.size() - 1);
        int index = busquedaBinaria(productos, titulo);
        if (index == -1) {
            JOptionPane.showMessageDialog(null, "No se encontro el producto");
            return;
        }
        Producto objProducto = productos.get(index);

        //colocar elementos
        objModel.addRow(new Object[]{objProducto.getId_libro(), objProducto.getTitulo(),
            objProducto.getAutor().toString(), objProducto.getEditorial().toString(),
            objProducto.getCategoria().toString(),
            objProducto.getIsbn(), objProducto.getFecha_publicacion(), objProducto.getIdioma(),
            objProducto.getPrecio(), objProducto.getCantidad()});

        //COLOCAR EL MODELO A LA TABLA
        jTable1.setModel(objModel);

    }

    //quicksort STOCK
    public static void quickSort(List<Producto> productos, int low, int high) {
        if (low < high) {
            int pi = partition(productos, low, high);

            quickSort(productos, low, pi - 1);
            quickSort(productos, pi + 1, high);
        }
    }

    private static int partition(List<Producto> productos, int low, int high) {
        Producto pivot = productos.get(high);
        int i = (low - 1);
        for (int j = low; j < high; j++) {
            if (productos.get(j).getCantidad() < pivot.getCantidad()) {
                i++;

                // Swap productos[i] and productos[j]
                Producto temp = productos.get(i);
                productos.set(i, productos.get(j));
                productos.set(j, temp);
            }
        }

        // Swap productos[i + 1] and productos[high] (or pivot)
        Producto temp = productos.get(i + 1);
        productos.set(i + 1, productos.get(high));
        productos.set(high, temp);

        return i + 1;
    }

    //quicksort Titulo
    public static void quickSortTitulo(List<Producto> productos, int low, int high) {
        if (low < high) {
            int pi = partitionTitulo(productos, low, high);

            quickSortTitulo(productos, low, pi - 1);  // Antes de pi
            quickSortTitulo(productos, pi + 1, high); // Después de pi
        }
    }

    private static int partitionTitulo(List<Producto> productos, int low, int high) {
        Producto pivot = productos.get(high);
        int i = (low - 1); // índice de elemento más pequeño

        for (int j = low; j < high; j++) {
            // Si el elemento actual es más pequeño o igual al pivot
            if (productos.get(j).getTitulo().compareTo(pivot.getTitulo()) <= 0) {
                i++;

                // Intercambiar productos.get(i) y productos.get(j)
                Producto temp = productos.get(i);
                productos.set(i, productos.get(j));
                productos.set(j, temp);
            }
        }

        // Intercambiar productos.get(i+1) y productos.get(high) (o pivot)
        Producto temp = productos.get(i + 1);
        productos.set(i + 1, productos.get(high));
        productos.set(high, temp);

        return i + 1;
    }

    //BUSQUEDA BINARIA
    public static int busquedaBinaria(List<Producto> productos, String titulo) {
        int low = 0;
        int high = productos.size() - 1;

        while (low <= high) {
            int mid = (low + high) / 2;
            Producto midVal = productos.get(mid);
            int cmp = midVal.getTitulo().compareTo(titulo);

            if (cmp < 0) {
                low = mid + 1;
            } else if (cmp > 0) {
                high = mid - 1;
            } else {
                return mid; // Título encontrado
            }
        }
        return -1; // Título no encontrado
    }

    //PDF
    private void pdf() {
        MessageFormat header = new MessageFormat("Usuarios");
        MessageFormat footer = new MessageFormat("Página {0}");

        try {
            PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
            set.add(OrientationRequested.LANDSCAPE);

            boolean complete = jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, set, false);
            if (complete) {
                System.out.println("Impresión completada.");
            } else {
                System.out.println("Impresión cancelada.");
            }
        } catch (PrinterException e) {
            System.err.println("Error durante la impresión: " + e.getMessage());
        }
    }
}
