/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.utp.view;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JFrame;

/*import pe.edu.utp.dto.ListaEnlazadaPedido;*/
public class Menu extends javax.swing.JFrame {
    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        ocultarMenuSecundario();
        
        JPInicio objInicio = new JPInicio();
        mostrarPanel(objInicio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEntrega = new javax.swing.JPanel();
        panelFondoNuevoPedido = new javax.swing.JPanel();
        btnAñadirPedido = new javax.swing.JButton();
        panelFondoActualizarPedido = new javax.swing.JPanel();
        btnActualizarPedido = new javax.swing.JButton();
        panelCliente = new javax.swing.JPanel();
        panelFondoNuevoCliente = new javax.swing.JPanel();
        btnNuevoCliente = new javax.swing.JButton();
        panelFondoGestionarCliente = new javax.swing.JPanel();
        btnGestionarClientes = new javax.swing.JButton();
        panelProducto = new javax.swing.JPanel();
        panelFondoNuevoLibro = new javax.swing.JPanel();
        btnNuevoLibro = new javax.swing.JButton();
        panelFondoGestionarLibro = new javax.swing.JPanel();
        btnGestionarLibros = new javax.swing.JButton();
        panelFondoActualizarLibro = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        panelReporte = new javax.swing.JPanel();
        panelFondoEstadoPedido = new javax.swing.JPanel();
        btnEstadoPedido = new javax.swing.JButton();
        panelFondoReporteVenta = new javax.swing.JPanel();
        btnReporteStock = new javax.swing.JButton();
        panelFondoReporteStock = new javax.swing.JPanel();
        btnReporteVentas = new javax.swing.JButton();
        panelUsuario = new javax.swing.JPanel();
        panelFondoNuevoUsuario = new javax.swing.JPanel();
        btnNuevoUsuario = new javax.swing.JButton();
        panelFondoGestionarUsuario = new javax.swing.JPanel();
        btnGestionarUsuario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        panelFondoSalir = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        panelFondoEntrega = new javax.swing.JPanel();
        btnEntrega = new javax.swing.JButton();
        panelFondoReportes = new javax.swing.JPanel();
        btnReportes = new javax.swing.JButton();
        panelFondoCliente = new javax.swing.JPanel();
        btnCliente = new javax.swing.JButton();
        panelFondoProducto = new javax.swing.JPanel();
        btnProducto = new javax.swing.JButton();
        panelFondoUsuario = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEntrega.setBackground(new java.awt.Color(51, 51, 51));
        panelEntrega.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelEntrega.setPreferredSize(new java.awt.Dimension(187, 300));
        panelEntrega.setRequestFocusEnabled(false);
        panelEntrega.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondoNuevoPedido.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoNuevoPedido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAñadirPedido.setBackground(new java.awt.Color(255, 153, 153));
        btnAñadirPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadirPedido.setText("Añadir Nuevo Pedido");
        btnAñadirPedido.setBorder(null);
        btnAñadirPedido.setContentAreaFilled(false);
        btnAñadirPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAñadirPedido.setFocusPainted(false);
        btnAñadirPedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAñadirPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAñadirPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAñadirPedidoMouseExited(evt);
            }
        });
        btnAñadirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirPedidoActionPerformed(evt);
            }
        });
        panelFondoNuevoPedido.add(btnAñadirPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelEntrega.add(panelFondoNuevoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelFondoActualizarPedido.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoActualizarPedido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizarPedido.setBackground(new java.awt.Color(255, 153, 153));
        btnActualizarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarPedido.setText("Actualizar Pedido");
        btnActualizarPedido.setBorder(null);
        btnActualizarPedido.setContentAreaFilled(false);
        btnActualizarPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizarPedido.setFocusPainted(false);
        btnActualizarPedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarPedidoMouseExited(evt);
            }
        });
        btnActualizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPedidoActionPerformed(evt);
            }
        });
        panelFondoActualizarPedido.add(btnActualizarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelEntrega.add(panelFondoActualizarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 40));

        getContentPane().add(panelEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 180, 80));

        panelCliente.setBackground(new java.awt.Color(51, 51, 51));
        panelCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCliente.setPreferredSize(new java.awt.Dimension(187, 300));
        panelCliente.setRequestFocusEnabled(false);
        panelCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondoNuevoCliente.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoNuevoCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevoCliente.setBackground(new java.awt.Color(255, 153, 153));
        btnNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCliente.setText("Nuevo Cliente");
        btnNuevoCliente.setBorder(null);
        btnNuevoCliente.setContentAreaFilled(false);
        btnNuevoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevoCliente.setFocusPainted(false);
        btnNuevoCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevoClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevoClienteMouseExited(evt);
            }
        });
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });
        panelFondoNuevoCliente.add(btnNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelCliente.add(panelFondoNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelFondoGestionarCliente.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoGestionarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGestionarClientes.setBackground(new java.awt.Color(255, 153, 153));
        btnGestionarClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarClientes.setText("Gestionar Clientes");
        btnGestionarClientes.setBorder(null);
        btnGestionarClientes.setContentAreaFilled(false);
        btnGestionarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionarClientes.setFocusPainted(false);
        btnGestionarClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGestionarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionarClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionarClientesMouseExited(evt);
            }
        });
        btnGestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarClientesActionPerformed(evt);
            }
        });
        panelFondoGestionarCliente.add(btnGestionarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelCliente.add(panelFondoGestionarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 40));

        getContentPane().add(panelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 180, 80));

        panelProducto.setBackground(new java.awt.Color(51, 51, 51));
        panelProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelProducto.setPreferredSize(new java.awt.Dimension(187, 300));
        panelProducto.setRequestFocusEnabled(false);
        panelProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondoNuevoLibro.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoNuevoLibro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevoLibro.setBackground(new java.awt.Color(255, 153, 153));
        btnNuevoLibro.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoLibro.setText("Nuevo Libro");
        btnNuevoLibro.setBorder(null);
        btnNuevoLibro.setContentAreaFilled(false);
        btnNuevoLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevoLibro.setFocusPainted(false);
        btnNuevoLibro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevoLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevoLibroMouseExited(evt);
            }
        });
        btnNuevoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoLibroActionPerformed(evt);
            }
        });
        panelFondoNuevoLibro.add(btnNuevoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelProducto.add(panelFondoNuevoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelFondoGestionarLibro.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoGestionarLibro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGestionarLibros.setBackground(new java.awt.Color(255, 153, 153));
        btnGestionarLibros.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarLibros.setText("Gestionar Libros");
        btnGestionarLibros.setBorder(null);
        btnGestionarLibros.setContentAreaFilled(false);
        btnGestionarLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionarLibros.setFocusPainted(false);
        btnGestionarLibros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGestionarLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionarLibrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionarLibrosMouseExited(evt);
            }
        });
        btnGestionarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarLibrosActionPerformed(evt);
            }
        });
        panelFondoGestionarLibro.add(btnGestionarLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelProducto.add(panelFondoGestionarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 40));

        panelFondoActualizarLibro.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoActualizarLibro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setBackground(new java.awt.Color(255, 153, 153));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizar.setFocusPainted(false);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarMouseExited(evt);
            }
        });
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        panelFondoActualizarLibro.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelProducto.add(panelFondoActualizarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 40));

        getContentPane().add(panelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 180, 120));

        panelReporte.setBackground(new java.awt.Color(51, 51, 51));
        panelReporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelReporte.setPreferredSize(new java.awt.Dimension(187, 300));
        panelReporte.setRequestFocusEnabled(false);
        panelReporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondoEstadoPedido.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoEstadoPedido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEstadoPedido.setBackground(new java.awt.Color(255, 153, 153));
        btnEstadoPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnEstadoPedido.setText("Estado de Pedido");
        btnEstadoPedido.setBorder(null);
        btnEstadoPedido.setContentAreaFilled(false);
        btnEstadoPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEstadoPedido.setFocusPainted(false);
        btnEstadoPedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstadoPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEstadoPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEstadoPedidoMouseExited(evt);
            }
        });
        btnEstadoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoPedidoActionPerformed(evt);
            }
        });
        panelFondoEstadoPedido.add(btnEstadoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelReporte.add(panelFondoEstadoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelFondoReporteVenta.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoReporteVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReporteStock.setBackground(new java.awt.Color(255, 153, 153));
        btnReporteStock.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteStock.setText("Reporte de Stock");
        btnReporteStock.setBorder(null);
        btnReporteStock.setContentAreaFilled(false);
        btnReporteStock.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReporteStock.setFocusPainted(false);
        btnReporteStock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporteStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporteStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteStockMouseExited(evt);
            }
        });
        btnReporteStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteStockActionPerformed(evt);
            }
        });
        panelFondoReporteVenta.add(btnReporteStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelReporte.add(panelFondoReporteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 40));

        panelFondoReporteStock.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoReporteStock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReporteVentas.setBackground(new java.awt.Color(255, 153, 153));
        btnReporteVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteVentas.setText("Reporte de Ventas");
        btnReporteVentas.setBorder(null);
        btnReporteVentas.setContentAreaFilled(false);
        btnReporteVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReporteVentas.setFocusPainted(false);
        btnReporteVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporteVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporteVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteVentasMouseExited(evt);
            }
        });
        btnReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteVentasActionPerformed(evt);
            }
        });
        panelFondoReporteStock.add(btnReporteVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelReporte.add(panelFondoReporteStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 40));

        getContentPane().add(panelReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 180, 120));

        panelUsuario.setBackground(new java.awt.Color(51, 51, 51));
        panelUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondoNuevoUsuario.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoNuevoUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevoUsuario.setBackground(new java.awt.Color(255, 153, 153));
        btnNuevoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoUsuario.setText("Nuevo Usuario");
        btnNuevoUsuario.setBorder(null);
        btnNuevoUsuario.setContentAreaFilled(false);
        btnNuevoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevoUsuario.setFocusPainted(false);
        btnNuevoUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevoUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevoUsuarioMouseExited(evt);
            }
        });
        btnNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuarioActionPerformed(evt);
            }
        });
        panelFondoNuevoUsuario.add(btnNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelUsuario.add(panelFondoNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelFondoGestionarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoGestionarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGestionarUsuario.setBackground(new java.awt.Color(255, 153, 153));
        btnGestionarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarUsuario.setText("Gestionar Usuario");
        btnGestionarUsuario.setBorder(null);
        btnGestionarUsuario.setContentAreaFilled(false);
        btnGestionarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionarUsuario.setFocusPainted(false);
        btnGestionarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGestionarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionarUsuarioMouseExited(evt);
            }
        });
        btnGestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarUsuarioActionPerformed(evt);
            }
        });
        panelFondoGestionarUsuario.add(btnGestionarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelUsuario.add(panelFondoGestionarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 40));

        getContentPane().add(panelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 180, 80));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 820, 600));

        panelMenu.setBackground(new java.awt.Color(51, 51, 51));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondoSalir.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(255, 153, 153));
        btnSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/cerrar-sesion (1).png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.setFocusPainted(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelFondoSalir.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(panelFondoSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 180, 40));

        panelFondoEntrega.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoEntrega.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEntrega.setBackground(new java.awt.Color(255, 153, 153));
        btnEntrega.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEntrega.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/entrega-rapida (1).png"))); // NOI18N
        btnEntrega.setText("ENTREGA");
        btnEntrega.setBorder(null);
        btnEntrega.setContentAreaFilled(false);
        btnEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEntrega.setFocusPainted(false);
        btnEntrega.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEntrega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntregaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntregaMouseExited(evt);
            }
        });
        btnEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregaActionPerformed(evt);
            }
        });
        panelFondoEntrega.add(btnEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(panelFondoEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 180, 40));

        panelFondoReportes.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReportes.setBackground(new java.awt.Color(255, 153, 153));
        btnReportes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/informe-seo (1).png"))); // NOI18N
        btnReportes.setText("REPORTES");
        btnReportes.setBorder(null);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReportes.setFocusPainted(false);
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportesMouseExited(evt);
            }
        });
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        panelFondoReportes.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(panelFondoReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 180, 40));

        panelFondoCliente.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCliente.setBackground(new java.awt.Color(255, 153, 153));
        btnCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/personas (1).png"))); // NOI18N
        btnCliente.setText("CLIENTE");
        btnCliente.setBorder(null);
        btnCliente.setContentAreaFilled(false);
        btnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCliente.setFocusPainted(false);
        btnCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClienteMouseExited(evt);
            }
        });
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        panelFondoCliente.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(panelFondoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 180, 40));

        panelFondoProducto.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProducto.setBackground(new java.awt.Color(255, 153, 153));
        btnProducto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/caja-negra (1).png"))); // NOI18N
        btnProducto.setText("PRODUCTO");
        btnProducto.setBorder(null);
        btnProducto.setContentAreaFilled(false);
        btnProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProducto.setFocusPainted(false);
        btnProducto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductoMouseExited(evt);
            }
        });
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });
        panelFondoProducto.add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(panelFondoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 180, 40));

        panelFondoUsuario.setBackground(new java.awt.Color(51, 51, 51));
        panelFondoUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUsuario.setBackground(new java.awt.Color(153, 102, 255));
        btnUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/usuario (1).png"))); // NOI18N
        btnUsuario.setText("USUARIO");
        btnUsuario.setToolTipText("");
        btnUsuario.setBorder(null);
        btnUsuario.setBorderPainted(false);
        btnUsuario.setContentAreaFilled(false);
        btnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUsuario.setDefaultCapable(false);
        btnUsuario.setFocusPainted(false);
        btnUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUsuario.setIconTextGap(9);
        btnUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsuarioMouseExited(evt);
            }
        });
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        panelFondoUsuario.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(panelFondoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 180, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/libro (2) (1).png"))); // NOI18N
        panelMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 30, 110, 110));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/img/expediente (1).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelMenu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 40, 30));

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarUsuarioActionPerformed
        fondoMouseClicked(panelFondoGestionarUsuario);
        JPGestionarUsuario objGestionUsuario = new JPGestionarUsuario();
        mostrarPanel(objGestionUsuario);
        ocultarMenuSecundario();
    }//GEN-LAST:event_btnGestionarUsuarioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioActionPerformed
        fondoMouseClicked(panelFondoNuevoUsuario);
        JFNuevoUsuario objNuevoUsuario = new JFNuevoUsuario();
        mostrarFrame(objNuevoUsuario);
        /*InternalNuevoUsuario objNuevoUsuario = new InternalNuevoUsuario();//modificar
        objNuevoUsuario.setVisible(true);
        jPanel2.add(objNuevoUsuario);*/
    }//GEN-LAST:event_btnNuevoUsuarioActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        protocoloMouseClicked(panelUsuario, panelFondoUsuario);
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnNuevoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoLibroActionPerformed
        fondoMouseClicked(panelFondoNuevoLibro);
        JFNuevoProducto objNuevoProducto = new JFNuevoProducto();
        mostrarFrame(objNuevoProducto);
    }//GEN-LAST:event_btnNuevoLibroActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        fondoMouseClicked(panelFondoActualizarLibro);
        JPActualizarProducto objActualizarProducto = new JPActualizarProducto();
        mostrarPanel(objActualizarProducto);
        ocultarMenuSecundario();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnGestionarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarLibrosActionPerformed
        fondoMouseClicked(panelFondoGestionarLibro);
        JPGestionProducto objGestionProducto = new JPGestionProducto();
        mostrarPanel(objGestionProducto);
        ocultarMenuSecundario();
    }//GEN-LAST:event_btnGestionarLibrosActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        protocoloMouseClicked(panelProducto, panelFondoProducto);
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        protocoloMouseClicked(panelCliente, panelFondoCliente);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        protocoloMouseClicked(panelReporte, panelFondoReportes);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregaActionPerformed
        protocoloMouseClicked(panelEntrega, panelFondoEntrega);
    }//GEN-LAST:event_btnEntregaActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        fondoMouseClicked(panelFondoNuevoCliente);
        JFNuevoCliente objNuevoCliente = new JFNuevoCliente();
        mostrarFrame(objNuevoCliente);
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnGestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarClientesActionPerformed
        fondoMouseClicked(panelFondoGestionarCliente);
        JPGestionarClientes objGestionCliente = new JPGestionarClientes();
        mostrarPanel(objGestionCliente);
        ocultarMenuSecundario();
    }//GEN-LAST:event_btnGestionarClientesActionPerformed

    private void btnEstadoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoPedidoActionPerformed
        fondoMouseClicked(panelFondoEstadoPedido);
        JPEstadoPedido objEstadoPedido = new JPEstadoPedido();
        mostrarPanel(objEstadoPedido);
        ocultarMenuSecundario();
    }//GEN-LAST:event_btnEstadoPedidoActionPerformed

    private void btnReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteVentasActionPerformed
        fondoMouseClicked(panelFondoReporteStock);
        JPReporteVentas objReporteVenta = new JPReporteVentas();
        mostrarPanel(objReporteVenta);
        ocultarMenuSecundario();
    }//GEN-LAST:event_btnReporteVentasActionPerformed

    private void btnReporteStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteStockActionPerformed
        fondoMouseClicked(panelFondoReporteVenta);
        JPReporteStock objReporteStock = new JPReporteStock();
        mostrarPanel(objReporteStock);
        ocultarMenuSecundario();
    }//GEN-LAST:event_btnReporteStockActionPerformed

    private void btnAñadirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirPedidoActionPerformed
        fondoMouseClicked(panelFondoNuevoPedido);
        JFNuevoPedidoCliente objNuevoPedido = new JFNuevoPedidoCliente();
        mostrarFrame(objNuevoPedido);
    }//GEN-LAST:event_btnAñadirPedidoActionPerformed

    private void btnActualizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPedidoActionPerformed
        fondoMouseClicked(panelFondoActualizarPedido);
        JPActualizarPedido objActualizarPedido = new JPActualizarPedido();
        mostrarPanel(objActualizarPedido);
        ocultarMenuSecundario();
    }//GEN-LAST:event_btnActualizarPedidoActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        ocultarMenuSecundario();
        quitarFondoBotones();
    }//GEN-LAST:event_jPanel2MouseClicked

    /*Animaciona al pasar por los botones*/
    private void btnUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMouseEntered
        protocoloFondoMouseEntered(panelUsuario, panelFondoUsuario);
    }//GEN-LAST:event_btnUsuarioMouseEntered

    private void btnUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMouseExited
        protocoloFondoMouseExited(panelUsuario, panelFondoUsuario);
    }//GEN-LAST:event_btnUsuarioMouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        fondoMouseEntered(panelFondoSalir);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        fondoMouseExited(panelFondoSalir);
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMouseEntered
        protocoloFondoMouseEntered(panelProducto, panelFondoProducto);
    }//GEN-LAST:event_btnProductoMouseEntered

    private void btnProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMouseExited
        protocoloFondoMouseExited(panelProducto, panelFondoProducto);
    }//GEN-LAST:event_btnProductoMouseExited

    private void btnClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseEntered
        protocoloFondoMouseEntered(panelCliente, panelFondoCliente);

    }//GEN-LAST:event_btnClienteMouseEntered

    private void btnClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseExited
        protocoloFondoMouseExited(panelCliente, panelFondoCliente);
    }//GEN-LAST:event_btnClienteMouseExited

    private void btnReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseEntered
        protocoloFondoMouseEntered(panelReporte, panelFondoReportes);

    }//GEN-LAST:event_btnReportesMouseEntered

    private void btnReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseExited
        protocoloFondoMouseExited(panelReporte, panelFondoReportes);
    }//GEN-LAST:event_btnReportesMouseExited

    private void btnEntregaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntregaMouseEntered
        protocoloFondoMouseEntered(panelEntrega, panelFondoEntrega);
    }//GEN-LAST:event_btnEntregaMouseEntered

    private void btnEntregaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntregaMouseExited
        protocoloFondoMouseExited(panelEntrega, panelFondoEntrega);
    }//GEN-LAST:event_btnEntregaMouseExited

    private void btnAñadirPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAñadirPedidoMouseEntered
        fondoMouseEntered(panelFondoNuevoPedido);
    }//GEN-LAST:event_btnAñadirPedidoMouseEntered

    private void btnNuevoUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioMouseEntered
        fondoMouseEntered(panelFondoNuevoUsuario);
    }//GEN-LAST:event_btnNuevoUsuarioMouseEntered

    private void btnNuevoUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioMouseExited
        fondoMouseExited(panelFondoNuevoUsuario);
    }//GEN-LAST:event_btnNuevoUsuarioMouseExited

    private void btnAñadirPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAñadirPedidoMouseExited
        fondoMouseExited(panelFondoNuevoPedido);
    }//GEN-LAST:event_btnAñadirPedidoMouseExited

    private void btnActualizarPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPedidoMouseEntered
        fondoMouseEntered(panelFondoActualizarPedido);
    }//GEN-LAST:event_btnActualizarPedidoMouseEntered

    private void btnActualizarPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPedidoMouseExited
        fondoMouseExited(panelFondoActualizarPedido);
    }//GEN-LAST:event_btnActualizarPedidoMouseExited

    private void btnNuevoClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoClienteMouseEntered
        fondoMouseEntered(panelFondoNuevoCliente);
    }//GEN-LAST:event_btnNuevoClienteMouseEntered

    private void btnNuevoClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoClienteMouseExited
        fondoMouseExited(panelFondoNuevoCliente);
    }//GEN-LAST:event_btnNuevoClienteMouseExited

    private void btnGestionarClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarClientesMouseEntered
        fondoMouseEntered(panelFondoGestionarCliente);
    }//GEN-LAST:event_btnGestionarClientesMouseEntered

    private void btnGestionarClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarClientesMouseExited
        fondoMouseExited(panelFondoGestionarCliente);
    }//GEN-LAST:event_btnGestionarClientesMouseExited

    private void btnNuevoLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoLibroMouseEntered
        fondoMouseEntered(panelFondoNuevoLibro);
    }//GEN-LAST:event_btnNuevoLibroMouseEntered

    private void btnNuevoLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoLibroMouseExited
        fondoMouseExited(panelFondoNuevoLibro);
    }//GEN-LAST:event_btnNuevoLibroMouseExited

    private void btnGestionarLibrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarLibrosMouseEntered
        fondoMouseEntered(panelFondoGestionarLibro);
    }//GEN-LAST:event_btnGestionarLibrosMouseEntered

    private void btnGestionarLibrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarLibrosMouseExited
        fondoMouseExited(panelFondoGestionarLibro);
    }//GEN-LAST:event_btnGestionarLibrosMouseExited

    private void btnActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseEntered
        fondoMouseEntered(panelFondoActualizarLibro);
    }//GEN-LAST:event_btnActualizarMouseEntered

    private void btnActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseExited
        fondoMouseExited(panelFondoActualizarLibro);
    }//GEN-LAST:event_btnActualizarMouseExited

    private void btnEstadoPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadoPedidoMouseEntered
        fondoMouseEntered(panelFondoEstadoPedido);
    }//GEN-LAST:event_btnEstadoPedidoMouseEntered

    private void btnEstadoPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadoPedidoMouseExited
        fondoMouseExited(panelFondoEstadoPedido);
    }//GEN-LAST:event_btnEstadoPedidoMouseExited

    private void btnReporteStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteStockMouseEntered
        fondoMouseEntered(panelFondoReporteVenta);
    }//GEN-LAST:event_btnReporteStockMouseEntered

    private void btnReporteStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteStockMouseExited
        fondoMouseExited(panelFondoReporteVenta);
    }//GEN-LAST:event_btnReporteStockMouseExited

    private void btnReporteVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteVentasMouseEntered
        fondoMouseEntered(panelFondoReporteStock);
    }//GEN-LAST:event_btnReporteVentasMouseEntered

    private void btnReporteVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteVentasMouseExited
        fondoMouseExited(panelFondoReporteStock);
    }//GEN-LAST:event_btnReporteVentasMouseExited

    private void btnGestionarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarUsuarioMouseEntered
        fondoMouseEntered(panelFondoGestionarUsuario);
    }//GEN-LAST:event_btnGestionarUsuarioMouseEntered

    private void btnGestionarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarUsuarioMouseExited
        fondoMouseExited(panelFondoGestionarUsuario);
    }//GEN-LAST:event_btnGestionarUsuarioMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JPHistorial objHistorial = new JPHistorial();
       mostrarPanel(objHistorial);
               
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
 
    
    private void ocultarMenuSecundario() {
        panelCliente.setVisible(false);
        panelEntrega.setVisible(false);
        panelProducto.setVisible(false);
        panelReporte.setVisible(false);
        panelUsuario.setVisible(false);
    }
    
    private void mostrarMenuSecundario(JPanel panel) {
        panel.setVisible(true);
    }
    
    private void fondoMouseClicked(JPanel panelFondo) {
        panelFondo.setBackground(new Color(0, 0, 0));
    }
    
    private void protocoloMouseClicked(JPanel panelSubmenu, JPanel panelFondo) {
        quitarFondoBotones();
        fondoMouseClicked(panelFondo);
        if (panelSubmenu.isVisible()) {
            ocultarMenuSecundario();
        } else {
            ocultarMenuSecundario();
            mostrarMenuSecundario(panelSubmenu);
        }
    }
    
    private void fondoMouseEntered(JPanel panel) {
        panel.setBackground(new Color(102, 102, 102));
    }
    
    private void protocoloFondoMouseEntered(JPanel panelSubmenu, JPanel panelFondo) {
        if (!panelSubmenu.isVisible()) {
            fondoMouseEntered(panelFondo);
        }
    }
    
    private void fondoMouseExited(JPanel panel) {
        panel.setBackground(new Color(51, 51, 51));
    }
    
    private void protocoloFondoMouseExited(JPanel panelSubmenu, JPanel panelFondo) {
        if (!panelSubmenu.isVisible()) {
            fondoMouseExited(panelFondo);
        }
    }
    
    private void quitarFondoBotones() {
        fondoMouseExited(panelFondoUsuario);
        fondoMouseExited(panelFondoProducto);
        fondoMouseExited(panelFondoCliente);
        fondoMouseExited(panelFondoReportes);
        fondoMouseExited(panelFondoEntrega);
    }
    
    private void mostrarPanel(JPanel panel) {
        panel.setSize(820, 600);
        panel.setLocation(0, 0);
        jPanel2.removeAll();
        jPanel2.add(panel, BorderLayout.CENTER);
        jPanel2.revalidate();
        jPanel2.repaint();
    }
    
    private void mostrarFrame(JFrame frame) {
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizarPedido;
    private javax.swing.JButton btnAñadirPedido;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEntrega;
    private javax.swing.JButton btnEstadoPedido;
    private javax.swing.JButton btnGestionarClientes;
    private javax.swing.JButton btnGestionarLibros;
    private javax.swing.JButton btnGestionarUsuario;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnNuevoLibro;
    private javax.swing.JButton btnNuevoUsuario;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnReporteStock;
    private javax.swing.JButton btnReporteVentas;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelEntrega;
    private javax.swing.JPanel panelFondoActualizarLibro;
    private javax.swing.JPanel panelFondoActualizarPedido;
    private javax.swing.JPanel panelFondoCliente;
    private javax.swing.JPanel panelFondoEntrega;
    private javax.swing.JPanel panelFondoEstadoPedido;
    private javax.swing.JPanel panelFondoGestionarCliente;
    private javax.swing.JPanel panelFondoGestionarLibro;
    private javax.swing.JPanel panelFondoGestionarUsuario;
    private javax.swing.JPanel panelFondoNuevoCliente;
    private javax.swing.JPanel panelFondoNuevoLibro;
    private javax.swing.JPanel panelFondoNuevoPedido;
    private javax.swing.JPanel panelFondoNuevoUsuario;
    private javax.swing.JPanel panelFondoProducto;
    private javax.swing.JPanel panelFondoReporteStock;
    private javax.swing.JPanel panelFondoReporteVenta;
    private javax.swing.JPanel panelFondoReportes;
    private javax.swing.JPanel panelFondoSalir;
    private javax.swing.JPanel panelFondoUsuario;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelProducto;
    private javax.swing.JPanel panelReporte;
    private javax.swing.JPanel panelUsuario;
    // End of variables declaration//GEN-END:variables
}
